using './main.bicep'

// param resourceGroupName = 'foo'
param location = 'uksouth'
param vnetName = 'foovnet'
param subnetName = 'foosubnet'
param privateEndpointName = 'foopep'
param privateDnsZoneName = 'foodns'
param storageAccountName = 'foosa'
param appServicePlanName = 'fooasp'
param functionAppName = 'foofa'
